backend environment setup
DevHomies/LikeHome pull request #2
Opened 2023-02-21 04:53 UTC by xiyuanzhou

2023-02-21 05:20 UTC, TrustfulDev approved these changes
Looks good! Thanks for getting the backend environment started. I'll get Albany to start the react environment in the client folder.

2023-02-21 06:32 UTC, rhedgeco requested changes
Please add a `.gitignore` file and include the `_pycache_` folder. It currently contains compiled cpython that is machine specific, plus it can bloat the repo. Other than that, looks good! Just check up on that secret key for me

2023-02-21 06:32 UTC, rhedgeco commented on Server/Server/settings.py
> +SECRET_KEY = "django-insecure-_w=guh&@n^%ydou=0%47^!r^n-bz91se^b9cg&52xi3wnpi!9c"
I don't know if this is the actual secret key we will be using. Looks like an auto-generated django key. this should probably be replaced and also we should not keep the secret key in the public repo.

See how you would use an load the secret key from an environment variable instead, or however django suggests to do this in production. It looks like there is a comment above this that goes over that

2023-02-21 06:51 UTC, rhedgeco commented
Also we should be tracking development dependencies and using python virtual environments so that multiple developers will be using the same dependencies and environment.

If you can look into making a [`requirements.txt`](https://learnpython.com/blog/python-requirements-file/) file and testing it in a fresh [`venv`](https://docs.python.org/3/library/venv.html) that would be amazing so we don't hit problems down the road. (just be sure to add the `venv` folder to the `.gitignore` too since each person will have their own)

2023-02-22 04:05 UTC, rhedgeco requested changes
It looks like the `_pycache_` folder is still in the branch. You will have to delete it manually and push the delete changes. Since it was already tracked, git cant untrack it until you delete it.

`.gitignore` looks good tho and gj on the `requirements.txt`

2023-02-22 04:48 UTC, rhedgeco approved these changes
:+1:

2023-02-22 04:49 UTC, merged