Fetching the API
DevHomies/LikeHome pull request #38
Opened 2023-04-28 06:35 UTC by TrustfulDev

Fetches the API in the backend to get the hotels and display them on the search page.
NOTE: Filtering/sorting by amenities will break the entire website (Currently working on a fix for this)

2023-04-28 19:34 UTC, rhedgeco requested changes

2023-04-28 19:34 UTC, rhedgeco commented on Server/db.sqlite3
should we be committing the database to the github repo? Is this just to have all the rando hotel data shared across clones?

2023-04-28 21:08 UTC, TrustfulDev commented on Server/db.sqlite3
Hmm, you're on to something. Since Kha is working on a fix for the issues relating to the database, we can either hold off on merging or continue with the merge without the database.

2023-04-29 00:48 UTC, rhedgeco commented on Server/db.sqlite3
I think in terms of time, we can probably just keep it. If changes are made, and info is added to it, we can just merge that in from Khas branch. It is kind of impossible to review since it is just a binary blob, but that may be the fastest way forwards to get everyone working from the same spot.

2023-04-29 00:50 UTC, rhedgeco approved these changes
Looks good to me. Lets get it in.

2023-04-29 01:04 UTC, reddesignsguy approved these changes
sweet

2023-04-29 01:05 UTC, merged